# Q.1 What is total revenue generated by male and female customer ? 
SELECT gender, SUM(purchase_amount) as revenue
FROM mytable
GROUP BY gender;

# Q.2 Which customer used discount but still spent more than a average purchase amount ? 
SELECT customer_id, purchase_amount
FROM mytable
WHERE discount_applied = "Yes"
AND purchase_amount >= (SELECT AVG(purchase_amount) FROM mytable);

# Q.3 Which are the top 5 products with the highest review rating ? 
SELECT item_purchased, Round(avg(review_rating),2) as "Average product rating"
from mytable
group by item_purchased
order by avg(review_rating) desc
limit 5;

# Q.4 Compare the average purchase amouns between standard and express shipping ? 
SELECT shipping_type,
ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount
FROM mytable
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

# Q.5 Do subscribed customers spend more ? compare average spend and total revenue between subscribers and non- subscribers ? 
SELECT subscription_status,
count(customer_id) as total_customer,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from mytable
group by subscription_status
order by total_revenue, avg_spend desc ;

# Q.6 Which 5 products have the highest percentage of purchase with discount applied ? 
select item_purchased,
round(100 * sum(case when discount_applied = "Yes" then 1 else 0 end)/count(*),2) as discount_rate
from mytable
group by item_purchased
order by discount_rate desc
limit 5 ;

# Q.7 Segment customers into New, Returning and Loyal based on their total previous purchase and  ? 
with customer_type as (
select customer_id, previous_purchases,
case 
    when previous_purchases = 1 then 'NEW'
    when previous_purchases between 2 and 10 then 'RETURNING'
    else 'LOYAL'
    end as customer_segments
from mytable )
select customer_segments, count(*) as No_of_customers
from customer_type
group by customer_segments ;

# Q.8 What are the top 3 most purchased products within the each category ? 
with item_count as(
select category, item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from mytable
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders from item_count
where item_rank <= 3 ;

# Q.9 Are customers who are repeat buyers ( more than 5 previous purchase ) also likely to subscribe ? 
select subscription_status, count(customer_id) as 'repeat buyers'
from mytable
where previous_purchases > 5
group by subscription_status ;

# Q.10 What is the revenue contribution of each age group ? 
select age_group,
sum(purchase_amount) as total_orders
from mytable
group by age_group
order by total_orders desc
